/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/sphere.glb -o Sphere.jsx -r public 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useExplode } from '../hooks/useExplode';

export function Sphere2(props) {
  const { nodes, materials } = useGLTF('/models/sphere.glb');
  console.log(nodes);
  const group = useRef();

  useExplode(group, {
    distance: 6,
  });
  return (
    <group
      ref={group}
      {...props}
      dispose={null}>
      <mesh
        geometry={nodes.Sphere_cell001.geometry}
        material={nodes.Sphere_cell001.material}
        position={[0.743, -0.401, 0.241]}
      />
      <mesh
        geometry={nodes.Sphere_cell002.geometry}
        material={nodes.Sphere_cell002.material}
        position={[0, -0.251, 0.881]}
      />
      <mesh
        geometry={nodes.Sphere_cell007.geometry}
        material={nodes.Sphere_cell007.material}
        position={[-0.27, 0.33, -0.8]}
      />
      <mesh
        geometry={nodes.Sphere_cell010.geometry}
        material={nodes.Sphere_cell010.material}
        position={[0.115, -0.295, -0.813]}
      />
      <mesh
        geometry={nodes.Sphere_cell012.geometry}
        material={nodes.Sphere_cell012.material}
        position={[0.593, 0.416, -0.431]}
      />
      <mesh
        geometry={nodes.Sphere_cell015.geometry}
        material={nodes.Sphere_cell015.material}
        position={[-0.133, 0.948, 0.007]}
      />
      <mesh
        geometry={nodes.Sphere_cell019.geometry}
        material={nodes.Sphere_cell019.material}
        position={[0.423, -0.521, -0.502]}
      />
      <mesh
        geometry={nodes.Sphere_cell025.geometry}
        material={nodes.Sphere_cell025.material}
        position={[0.261, -0.766, 0.37]}
      />
      <mesh
        geometry={nodes.Sphere_cell037.geometry}
        material={nodes.Sphere_cell037.material}
        position={[-0.405, -0.42, -0.672]}
      />
      <mesh
        geometry={nodes.Sphere_cell039.geometry}
        material={nodes.Sphere_cell039.material}
        position={[-0.482, -0.605, 0.559]}
      />
      <mesh
        geometry={nodes.Sphere_cell040.geometry}
        material={nodes.Sphere_cell040.material}
        position={[-0.826, 0.484, -0.105]}
      />
      <mesh
        geometry={nodes.Sphere_cell043.geometry}
        material={nodes.Sphere_cell043.material}
        position={[0.505, 0.734, -0.101]}
      />
      <mesh
        geometry={nodes.Sphere_cell044.geometry}
        material={nodes.Sphere_cell044.material}
        position={[-0.193, -0.849, -0.298]}
      />
      <mesh
        geometry={nodes.Sphere_cell047.geometry}
        material={nodes.Sphere_cell047.material}
        position={[-0.201, 0.85, -0.362]}
      />
      <mesh
        geometry={nodes.Sphere_cell062.geometry}
        material={nodes.Sphere_cell062.material}
        position={[0.675, 0.144, 0.009]}
      />
      <mesh
        geometry={nodes.Sphere_cell064.geometry}
        material={nodes.Sphere_cell064.material}
        position={[-0.017, -0.708, -0.613]}
      />
      <mesh
        geometry={nodes.Sphere_cell067.geometry}
        material={nodes.Sphere_cell067.material}
        position={[0.239, 0.879, 0.175]}
      />
      <mesh
        geometry={nodes.Sphere_cell073.geometry}
        material={nodes.Sphere_cell073.material}
        position={[-0.764, -0.136, -0.505]}
      />
      <mesh
        geometry={nodes.Sphere_cell075.geometry}
        material={nodes.Sphere_cell075.material}
        position={[-0.163, 0.827, 0.417]}
      />
      <mesh
        geometry={nodes.Sphere_cell076.geometry}
        material={nodes.Sphere_cell076.material}
        position={[-0.261, 0.577, 0.025]}
      />
      <mesh
        geometry={nodes.Sphere_cell079.geometry}
        material={nodes.Sphere_cell079.material}
        position={[-0.596, 0.679, -0.201]}
      />
      <mesh
        geometry={nodes.Sphere_cell081.geometry}
        material={nodes.Sphere_cell081.material}
        position={[0.561, 0.367, 0.591]}
      />
      <mesh
        geometry={nodes.Sphere_cell082.geometry}
        material={nodes.Sphere_cell082.material}
        position={[0.108, -0.952, -0.093]}
      />
      <mesh
        geometry={nodes.Sphere_cell084.geometry}
        material={nodes.Sphere_cell084.material}
        position={[-0.788, -0.338, -0.039]}
      />
      <mesh
        geometry={nodes.Sphere_cell085.geometry}
        material={nodes.Sphere_cell085.material}
        position={[-0.113, 0.026, -0.468]}
      />
      <mesh
        geometry={nodes.Sphere_cell086.geometry}
        material={nodes.Sphere_cell086.material}
        position={[-0.688, -0.023, 0.596]}
      />
      <mesh
        geometry={nodes.Sphere_cell090.geometry}
        material={nodes.Sphere_cell090.material}
        position={[0.393, 0.012, -0.854]}
      />
      <mesh
        geometry={nodes.Sphere_cell092.geometry}
        material={nodes.Sphere_cell092.material}
        position={[-0.845, 0.303, 0.223]}
      />
      <mesh
        geometry={nodes.Sphere_cell093.geometry}
        material={nodes.Sphere_cell093.material}
        position={[-0.353, -0.793, 0.19]}
      />
      <mesh
        geometry={nodes.Sphere_cell094.geometry}
        material={nodes.Sphere_cell094.material}
        position={[-0.684, 0.232, -0.257]}
      />
      <mesh
        geometry={nodes.Sphere_cell096.geometry}
        material={nodes.Sphere_cell096.material}
        position={[-0.12, -0.584, 0.716]}
      />
      <mesh
        geometry={nodes.Sphere_cell098.geometry}
        material={nodes.Sphere_cell098.material}
        position={[0.452, -0.08, 0.695]}
      />
      <mesh
        geometry={nodes.Sphere_cell107.geometry}
        material={nodes.Sphere_cell107.material}
        position={[0.033, -0.352, -0.037]}
      />
      <mesh
        geometry={nodes.Sphere_cell109.geometry}
        material={nodes.Sphere_cell109.material}
        position={[0.123, 0.402, -0.816]}
      />
      <mesh
        geometry={nodes.Sphere_cell112.geometry}
        material={nodes.Sphere_cell112.material}
        position={[-0.38, -0.263, 0.678]}
      />
      <mesh
        geometry={nodes.Sphere_cell113.geometry}
        material={nodes.Sphere_cell113.material}
        position={[0.441, -0.777, -0.271]}
      />
      <mesh
        geometry={nodes.Sphere_cell114.geometry}
        material={nodes.Sphere_cell114.material}
        position={[0.14, 0.13, 0.928]}
      />
      <mesh
        geometry={nodes.Sphere_cell117.geometry}
        material={nodes.Sphere_cell117.material}
        position={[-0.434, 0.05, -0.804]}
      />
      <mesh
        geometry={nodes.Sphere_cell118.geometry}
        material={nodes.Sphere_cell118.material}
        position={[-0.151, 0.408, 0.721]}
      />
      <mesh
        geometry={nodes.Sphere_cell121.geometry}
        material={nodes.Sphere_cell121.material}
        position={[-0.55, -0.732, -0.266]}
      />
      <mesh
        geometry={nodes.Sphere_cell124.geometry}
        material={nodes.Sphere_cell124.material}
        position={[0.444, -0.399, 0.724]}
      />
      <mesh
        geometry={nodes.Sphere_cell125.geometry}
        material={nodes.Sphere_cell125.material}
        position={[0.79, -0.212, -0.39]}
      />
      <mesh
        geometry={nodes.Sphere_cell123_cell.geometry}
        material={nodes.Sphere_cell123_cell.material}
        position={[-0.189, 0.722, -0.632]}
      />
      <mesh
        geometry={nodes.Sphere_cell123_cell002.geometry}
        material={nodes.Sphere_cell123_cell002.material}
        position={[-0.046, 0.689, -0.633]}
      />
      <mesh
        geometry={nodes.Sphere_cell123_cell003.geometry}
        material={nodes.Sphere_cell123_cell003.material}
        position={[-0.079, 0.816, -0.561]}
      />
      <mesh
        geometry={nodes.Sphere_cell123_cell005.geometry}
        material={nodes.Sphere_cell123_cell005.material}
        position={[0.094, 0.792, -0.521]}
      />
      <mesh
        geometry={nodes.Sphere_cell123_cell006.geometry}
        material={nodes.Sphere_cell123_cell006.material}
        position={[0.23, 0.771, -0.573]}
      />
      <mesh
        geometry={nodes.Sphere_cell123_cell007.geometry}
        material={nodes.Sphere_cell123_cell007.material}
        position={[0.154, 0.734, -0.62]}
      />
      <mesh
        geometry={nodes.Sphere_cell122_cell001.geometry}
        material={nodes.Sphere_cell122_cell001.material}
        position={[0.165, -0.534, 0.826]}
      />
      <mesh
        geometry={nodes.Sphere_cell122_cell002.geometry}
        material={nodes.Sphere_cell122_cell002.material}
        position={[0.142, -0.643, 0.74]}
      />
      <mesh
        geometry={nodes.Sphere_cell122_cell003.geometry}
        material={nodes.Sphere_cell122_cell003.material}
        position={[0.169, -0.608, 0.758]}
      />
      <mesh
        geometry={nodes.Sphere_cell122_cell004.geometry}
        material={nodes.Sphere_cell122_cell004.material}
        position={[0.157, -0.569, 0.797]}
      />
      <mesh
        geometry={nodes.Sphere_cell122_cell005.geometry}
        material={nodes.Sphere_cell122_cell005.material}
        position={[0.144, -0.579, 0.795]}
      />
      <mesh
        geometry={nodes.Sphere_cell122_cell006.geometry}
        material={nodes.Sphere_cell122_cell006.material}
        position={[0.182, -0.555, 0.799]}
      />
      <mesh
        geometry={nodes.Sphere_cell122_cell007.geometry}
        material={nodes.Sphere_cell122_cell007.material}
        position={[0.126, -0.632, 0.755]}
      />
      <mesh
        geometry={nodes.Sphere_cell119_cell001.geometry}
        material={nodes.Sphere_cell119_cell001.material}
        position={[0.677, 0.596, 0.391]}
      />
      <mesh
        geometry={nodes.Sphere_cell119_cell002.geometry}
        material={nodes.Sphere_cell119_cell002.material}
        position={[0.888, 0.338, 0.253]}
      />
      <mesh
        geometry={nodes.Sphere_cell119_cell003.geometry}
        material={nodes.Sphere_cell119_cell003.material}
        position={[0.801, 0.439, 0.343]}
      />
      <mesh
        geometry={nodes.Sphere_cell119_cell005.geometry}
        material={nodes.Sphere_cell119_cell005.material}
        position={[0.746, 0.54, 0.365]}
      />
      <mesh
        geometry={nodes.Sphere_cell119_cell007.geometry}
        material={nodes.Sphere_cell119_cell007.material}
        position={[0.722, 0.488, 0.467]}
      />
      <mesh
        geometry={nodes.Sphere_cell116_cell001.geometry}
        material={nodes.Sphere_cell116_cell001.material}
        position={[0.798, 0.113, -0.58]}
      />
      <mesh
        geometry={nodes.Sphere_cell116_cell005.geometry}
        material={nodes.Sphere_cell116_cell005.material}
        position={[0.82, 0.109, -0.549]}
      />
      <mesh
        geometry={nodes.Sphere_cell116_cell006.geometry}
        material={nodes.Sphere_cell116_cell006.material}
        position={[0.831, 0.177, -0.507]}
      />
      <mesh
        geometry={nodes.Sphere_cell116_cell007.geometry}
        material={nodes.Sphere_cell116_cell007.material}
        position={[0.885, 0.176, -0.411]}
      />
      <mesh
        geometry={nodes.Sphere_cell108_cell001.geometry}
        material={nodes.Sphere_cell108_cell001.material}
        position={[-0.276, 0.723, 0.624]}
      />
      <mesh
        geometry={nodes.Sphere_cell108_cell002.geometry}
        material={nodes.Sphere_cell108_cell002.material}
        position={[-0.346, 0.714, 0.594]}
      />
      <mesh
        geometry={nodes.Sphere_cell108_cell003.geometry}
        material={nodes.Sphere_cell108_cell003.material}
        position={[-0.399, 0.697, 0.588]}
      />
      <mesh
        geometry={nodes.Sphere_cell108_cell004.geometry}
        material={nodes.Sphere_cell108_cell004.material}
        position={[-0.369, 0.718, 0.579]}
      />
      <mesh
        geometry={nodes.Sphere_cell108_cell005.geometry}
        material={nodes.Sphere_cell108_cell005.material}
        position={[-0.458, 0.71, 0.529]}
      />
      <mesh
        geometry={nodes.Sphere_cell108_cell006.geometry}
        material={nodes.Sphere_cell108_cell006.material}
        position={[-0.409, 0.706, 0.563]}
      />
      <mesh
        geometry={nodes.Sphere_cell108_cell007.geometry}
        material={nodes.Sphere_cell108_cell007.material}
        position={[-0.381, 0.716, 0.562]}
      />
      <mesh
        geometry={nodes.Sphere_cell102_cell.geometry}
        material={nodes.Sphere_cell102_cell.material}
        position={[-0.557, -0.756, 0.237]}
      />
      <mesh
        geometry={nodes.Sphere_cell102_cell001.geometry}
        material={nodes.Sphere_cell102_cell001.material}
        position={[-0.635, -0.669, 0.321]}
      />
      <mesh
        geometry={nodes.Sphere_cell102_cell003.geometry}
        material={nodes.Sphere_cell102_cell003.material}
        position={[-0.69, -0.498, 0.371]}
      />
      <mesh
        geometry={nodes.Sphere_cell102_cell005.geometry}
        material={nodes.Sphere_cell102_cell005.material}
        position={[-0.564, -0.639, 0.394]}
      />
      <mesh
        geometry={nodes.Sphere_cell102_cell006.geometry}
        material={nodes.Sphere_cell102_cell006.material}
        position={[-0.688, -0.619, 0.196]}
      />
      <mesh
        geometry={nodes.Sphere_cell102_cell007.geometry}
        material={nodes.Sphere_cell102_cell007.material}
        position={[-0.47, -0.753, 0.382]}
      />
      <mesh
        geometry={nodes.Sphere_cell029_cell002.geometry}
        material={nodes.Sphere_cell029_cell002.material}
        position={[0.569, -0.456, -0.672]}
      />
      <mesh
        geometry={nodes.Sphere_cell029_cell003.geometry}
        material={nodes.Sphere_cell029_cell003.material}
        position={[0.526, -0.32, -0.769]}
      />
      <mesh
        geometry={nodes.Sphere_cell029_cell004.geometry}
        material={nodes.Sphere_cell029_cell004.material}
        position={[0.534, -0.262, -0.773]}
      />
      <mesh
        geometry={nodes.Sphere_cell029_cell005.geometry}
        material={nodes.Sphere_cell029_cell005.material}
        position={[0.446, -0.458, -0.763]}
      />
      <mesh
        geometry={nodes.Sphere_cell029_cell006.geometry}
        material={nodes.Sphere_cell029_cell006.material}
        position={[0.489, -0.42, -0.741]}
      />
      <mesh
        geometry={nodes.Sphere_cell023_cell.geometry}
        material={nodes.Sphere_cell023_cell.material}
        position={[-0.271, -0.837, 0.42]}
      />
      <mesh
        geometry={nodes.Sphere_cell023_cell001.geometry}
        material={nodes.Sphere_cell023_cell001.material}
        position={[0.001, -0.909, 0.276]}
      />
      <mesh
        geometry={nodes.Sphere_cell023_cell002.geometry}
        material={nodes.Sphere_cell023_cell002.material}
        position={[-0.161, -0.792, 0.492]}
      />
      <mesh
        geometry={nodes.Sphere_cell023_cell003.geometry}
        material={nodes.Sphere_cell023_cell003.material}
        position={[-0.119, -0.883, 0.349]}
      />
      <mesh
        geometry={nodes.Sphere_cell023_cell004.geometry}
        material={nodes.Sphere_cell023_cell004.material}
        position={[0.009, -0.895, 0.436]}
      />
      <mesh
        geometry={nodes.Sphere_cell023_cell006.geometry}
        material={nodes.Sphere_cell023_cell006.material}
        position={[-0.012, -0.794, 0.453]}
      />
      <mesh
        geometry={nodes.Sphere_cell021_cell.geometry}
        material={nodes.Sphere_cell021_cell.material}
        position={[-0.157, -0.943, 0.013]}
      />
      <mesh
        geometry={nodes.Sphere_cell021_cell002.geometry}
        material={nodes.Sphere_cell021_cell002.material}
        position={[0.013, -0.943, 0.137]}
      />
      <mesh
        geometry={nodes.Sphere_cell021_cell004.geometry}
        material={nodes.Sphere_cell021_cell004.material}
        position={[-0.088, -0.983, 0.116]}
      />
      <mesh
        geometry={nodes.Sphere_cell021_cell005.geometry}
        material={nodes.Sphere_cell021_cell005.material}
        position={[-0.025, -0.917, 0.025]}
      />
      <mesh
        geometry={nodes.Sphere_cell021_cell007.geometry}
        material={nodes.Sphere_cell021_cell007.material}
        position={[-0.205, -0.919, 0.121]}
      />
      <mesh
        geometry={nodes.Sphere_cell017_cell.geometry}
        material={nodes.Sphere_cell017_cell.material}
        position={[0.14, -0.717, 0.668]}
      />
      <mesh
        geometry={nodes.Sphere_cell017_cell001.geometry}
        material={nodes.Sphere_cell017_cell001.material}
        position={[-0.113, -0.771, 0.619]}
      />
      <mesh
        geometry={nodes.Sphere_cell017_cell002.geometry}
        material={nodes.Sphere_cell017_cell002.material}
        position={[0.046, -0.741, 0.639]}
      />
      <mesh
        geometry={nodes.Sphere_cell017_cell003.geometry}
        material={nodes.Sphere_cell017_cell003.material}
        position={[0.046, -0.819, 0.561]}
      />
      <mesh
        geometry={nodes.Sphere_cell017_cell007.geometry}
        material={nodes.Sphere_cell017_cell007.material}
        position={[0.108, -0.797, 0.589]}
      />
      <mesh
        geometry={nodes.Sphere_cell014_cell.geometry}
        material={nodes.Sphere_cell014_cell.material}
        position={[-0.568, 0.486, 0.618]}
      />
      <mesh
        geometry={nodes.Sphere_cell014_cell002.geometry}
        material={nodes.Sphere_cell014_cell002.material}
        position={[-0.459, 0.624, 0.624]}
      />
      <mesh
        geometry={nodes.Sphere_cell014_cell003.geometry}
        material={nodes.Sphere_cell014_cell003.material}
        position={[-0.489, 0.586, 0.63]}
      />
      <mesh
        geometry={nodes.Sphere_cell014_cell004.geometry}
        material={nodes.Sphere_cell014_cell004.material}
        position={[-0.51, 0.664, 0.505]}
      />
      <mesh
        geometry={nodes.Sphere_cell014_cell005.geometry}
        material={nodes.Sphere_cell014_cell005.material}
        position={[-0.625, 0.505, 0.509]}
      />
      <mesh
        geometry={nodes.Sphere_cell014_cell006.geometry}
        material={nodes.Sphere_cell014_cell006.material}
        position={[-0.558, 0.604, 0.477]}
      />
      <mesh
        geometry={nodes.Sphere_cell014_cell007.geometry}
        material={nodes.Sphere_cell014_cell007.material}
        position={[-0.623, 0.675, 0.368]}
      />
      <mesh
        geometry={nodes.Sphere_cell_cell.geometry}
        material={nodes.Sphere_cell_cell.material}
        position={[-0.438, 0.875, -0.177]}
      />
      <mesh
        geometry={nodes.Sphere_cell_cell001.geometry}
        material={nodes.Sphere_cell_cell001.material}
        position={[-0.44, 0.875, 0.004]}
      />
      <mesh
        geometry={nodes.Sphere_cell_cell002.geometry}
        material={nodes.Sphere_cell_cell002.material}
        position={[-0.436, 0.878, -0.094]}
      />
      <mesh
        geometry={nodes.Sphere_cell_cell005.geometry}
        material={nodes.Sphere_cell_cell005.material}
        position={[-0.439, 0.871, -0.203]}
      />
      <mesh
        geometry={nodes.Sphere_cell_cell007.geometry}
        material={nodes.Sphere_cell_cell007.material}
        position={[-0.435, 0.88, -0.151]}
      />
    </group>
  );
}

useGLTF.preload('/models/sphere.glb');
